DOMAIN = "modbus_custom_sensors"

SENSOR_LIST = [
    {
        "name": "Voltage",
        "unique_id": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5000,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "V",
        "scan_interval": 5,
    },
    {
        "name": "L1 Voltage",
        "unique_id": "L1V",
        "device_class": "voltage",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5002,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "V",
        "scan_interval": 5,
    },
    {
        "name": "L2 Voltage",
        "unique_id": "L2V",
        "device_class": "voltage",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5004,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "V",
        "scan_interval": 5,
    },
    {
        "name": "L3 Voltage",
        "unique_id": "L3V",
        "device_class": "voltage",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5006,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "V",
        "scan_interval": 5,
    },
    {
        "name": "Grid frequency",
        "unique_id": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5008,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "Hz",
        "scan_interval": 5,
    },
    {
        "name": "Current",
        "unique_id": "A",
        "device_class": "current",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x500A,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "A",
        "scan_interval": 5,
    },
    {
        "name": "L1 Current",
        "unique_id": "L1A",
        "device_class": "current",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x500C,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "A",
        "scan_interval": 5,
    },
    {
        "name": "L2 Current",
        "unique_id": "L2A",
        "device_class": "current",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x500E,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "A",
        "scan_interval": 5,
    },
    {
        "name": "L3 Current",
        "unique_id": "L3A",
        "device_class": "current",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5010,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "A",
        "scan_interval": 5,
    },
    {
        "name": "Total active power",
        "unique_id": "TAP",
        "device_class": "power",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5012,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "kW",
        "scan_interval": 5,
    },
    {
        "name": "L1 Active power",
        "unique_id": "TAP_L1",
        "device_class": "power",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5014,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "kW",
        "scan_interval": 5,
    },
    {
        "name": "L2 Active power",
        "unique_id": "TAP_L2",
        "device_class": "power",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5016,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "kW",
        "scan_interval": 5,
    },
    {
        "name": "L3 Active power",
        "unique_id": "TAP_L3",
        "device_class": "power",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5018,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "kW",
        "scan_interval": 5,
    },
    {
        "name": "Total reactive power",
        "unique_id": "TRP",
        "device_class": "power",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x501A,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "kVAr",
        "scan_interval": 5,
    },
    {
        "name": "L1 Reactive power",
        "unique_id": "TRP_L1",
        "device_class": "power",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x501C,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "kVAr",
        "scan_interval": 5,
    },
    {
        "name": "L2 Reactive power",
        "unique_id": "TRP_L2",
        "device_class": "power",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x501E,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "kVAr",
        "scan_interval": 5,
    },
    {
        "name": "L3 Reactive power",
        "unique_id": "TRP_L3",
        "device_class": "power",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5020,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "kVAr",
        "scan_interval": 5,
    },
    {
        "name": "Total apparent power",
        "unique_id": "TApP",
        "device_class": "power",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5022,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "kVA",
        "scan_interval": 5,
    },
    {
        "name": "L1 Apparent power",
        "unique_id": "TApP_L1",
        "device_class": "power",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5024,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "kVA",
        "scan_interval": 5,
    },
    {
        "name": "L2 Apparent power",
        "unique_id": "TApP_L2",
        "device_class": "power",
        "state_class": "measurement",
        "precision": 2,
        "address": 0x5026,
        "input_type": "holding",
        "count": 2,
        "data_type": "float32",
        "unit_of_measurement": "kVA"
    }
]
