# Modbus Plugin - Configuration and Sensor Mappings
# Source https://github.com/khaledemam/HA-inepro-Modbus/
# This file isn't a valid configuration file!

# Instructions:
# copy the custom_components directory to your HA custom_components directory
# Add ONE of the modbus: lines to your configuration.yaml
# Add the sensors below to your configuration.yaml 
#
# USB: Edit the file to update the connection settings
#
# LAN: Add a new secret to your secrets file - ModbusTCPgateway: <your inverter IP>


modbus: !include custom_components/HA-inepro-metering-Modbus/modbusUSB.yaml
# modbus: !include custom_components/HA-inepro-metering-Modbus/modbusLAN.yaml

